name: "Deploy Resume API Resources"

on:
  workflow_dispatch:
  push:
    branches:
      - '*release*'

jobs:
  deployment:
    name: "deployment"
    env:
      ARM_CLIENT_ID: ${{ secrets.ENTRA_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ENTRA_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ENTRA_TENANT_ID }} 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: "Terraform Init"
        id: init
        run: |
          cd ./terraform
          terraform init \
            -input=false \
            -backend-config="resource_group_name=${{ secrets.TERRAFORM_SA_RG_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.TERRAFORM_SA_NAME }}" \
            -backend-config="container_name=${{ secrets.TERRAFORM_SA_CONTAINER_NAME }}" \
            -backend-config="key=resumeapi.tfstate"

      - name: "Terraform Validate"
        id: validate
        run: |
          cd ./terraform
          terraform validate -no-color

      - name: "Terraform Plan"
        id: plan
        run: |
          cd ./terraform
          terraform plan \
            -out=tfplan \
            -input=false
          
      - name: "Terraform Apply"
        id: apply
        run: |
          cd ./terraform
          terraform apply -input=false tfplan